sudo: false

language: java

jdk:
   - openjdk8

addons:
  apt:
    packages:
      - realpath
  sonarcloud:
    organization: datadriven

install: true

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
script:
  - mvn spotless:check -B -V && travis_wait mvn install -B -V -Pallow-snapshots,with-coverage,travis -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=error || exit 1
  - export JAVA_HOME=$HOME/openjdk11
  - chmod u+x $TRAVIS_BUILD_DIR/install-jdk.sh
  - $TRAVIS_BUILD_DIR/install-jdk.sh --feature 11 --target $JAVA_HOME
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ] || [ "${TRAVIS_BRANCH}" == "master" ]; then mvn sonar:sonar -B -V -Pallow-snapshots,with-coverage,travis; fi

before_cache: rm -rf ~/.m2/repository/cz/o2/proxima || /bin/true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
